import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../components/layout/auth-provider";
import { RegisterFormStoreProvider } from "../providers/register-form-store-provider";

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin", "cyrillic"],
  display: "swap",
  fallback: ["system-ui", "Arial"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${onest.variable} antialiased`}>
        <RegisterFormStoreProvider>
          <AuthProvider>{children}</AuthProvider>
        </RegisterFormStoreProvider>
      </body>
    </html>
  );
}
